# Generated by Django 5.2.10 on 2026-03-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_deal_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='ends_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='starts_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
